create table jm2006_login (user_name varchar, password varchar);

SELECT * FROM JM2006_LOGIN

INSERT INTO JM2006_LOGIN VALUES('A', '1');


CREATE TABLE ACCOUNT_SUMMARY(
ID NUMBER,
CUST_NAME VARCHAR,
ACC_TYPE CHAR,
BALANCE DECIMAL
);
